import { matchItems, matchBbox, uniqueMatches } from './match.js';
const $ = selector => document.querySelector(selector);
const input = $('#imageInput'), dropZone = $('#dropZone'), findButton = $('#findButton'), targetText = $('#targetText'), matchMode = $('#matchMode'), verified = $('#verified'), scoreThresh = $('#scoreThresh'), threshValue = $('#threshValue'), workspace = $('#workspace'), canvas = $('#resultCanvas'), ctx = canvas.getContext('2d'), status = $('#status'), resultList = $('#resultList'), countBadge = $('#countBadge'), downloadButton = $('#downloadButton');
let image = null, imageFile = null, originalFileName = 'marked-image', latestMatches = [], lastBatch = null;
function setStatus(message) { status.textContent = message; }
function roundRectPath(x, y, w, h, r) { const radius = Math.max(0, Math.min(r, w / 2, h / 2)); ctx.beginPath(); ctx.moveTo(x + radius, y); ctx.arcTo(x + w, y, x + w, y + h, radius); ctx.arcTo(x + w, y + h, x, y + h, radius); ctx.arcTo(x, y + h, x, y, radius); ctx.arcTo(x, y, x + w, y, radius); ctx.closePath(); }
function draw(matches = []) { if (!image) return; canvas.width = image.naturalWidth; canvas.height = image.naturalHeight; ctx.drawImage(image, 0, 0); const scale = Math.max(2, canvas.width / 800); ctx.fillStyle = 'rgba(255, 212, 80, .42)'; matches.forEach(match => { const { x0, y0, x1, y1 } = matchBbox(match); const padX = scale * 2.5, padY = Math.max(scale * 2.5, (y1 - y0) * .22); const left = Math.max(0, x0 - padX), top = Math.max(0, y0 - padY), right = Math.min(canvas.width, x1 + padX), bottom = Math.min(canvas.height, y1 + padY); roundRectPath(left, top, right - left, bottom - top, scale * 3); ctx.fill(); }); }
function escapeHtml(value) { const el = document.createElement('div'); el.textContent = value; return el.innerHTML; }
function showMatches(matches) { latestMatches = matches; draw(matches); resultList.innerHTML = ''; countBadge.textContent = `${matches.length} 筆結果`; if (!matches.length) { setStatus('找不到相符文字。可降低最低信心度、使用擴大搜尋，或檢查輸入文字。'); downloadButton.classList.add('hidden'); return; } setStatus(`已標記 ${matches.length} 個相符位置。`); downloadButton.classList.remove('hidden'); matches.forEach((match, index) => { const li = document.createElement('li'); li.innerHTML = `<span class="match-text">${index + 1}. ${escapeHtml(match.text)}</span><span class="meta">信心度 ${Math.round(match.item.score * 100)}%</span>`; li.onclick = () => { draw([match]); canvas.scrollIntoView({ behavior: 'smooth', block: 'center' }); setTimeout(() => draw(latestMatches), 1300); }; resultList.appendChild(li); }); }
function recompute() { if (!lastBatch) return; showMatches(uniqueMatches(matchItems(lastBatch.items, lastBatch.query, matchMode.value, Number(scoreThresh.value)))); }
async function requestOcr() { const form = new FormData(); form.append('image', imageFile); form.append('upscale', String(verified.checked)); const response = await fetch('/api/ocr', { method: 'POST', body: form }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.detail || `後端回應 ${response.status}`); return data.items || []; }
async function recognise() { const query = targetText.value; if (!image || !query) { setStatus('請先上傳圖片並輸入要尋找的文字。'); return; } findButton.disabled = true; resultList.innerHTML = ''; countBadge.textContent = '辨識中'; try { setStatus('PaddleOCR 正在辨識圖片文字…首次使用可能需要下載模型，請稍候。'); lastBatch = { items: await requestOcr(), query }; recompute(); } catch (error) { console.error(error); setStatus(`辨識失敗：${error.message}`); countBadge.textContent = '發生錯誤'; } finally { findButton.disabled = false; } }
function loadFile(file) { if (!file || !file.type.startsWith('image/')) { setStatus('請選擇圖片檔案。'); return; } const reader = new FileReader(); reader.onload = () => { image = new Image(); image.onload = () => { imageFile = file; originalFileName = file.name.replace(/\.[^.]+$/, '') || originalFileName; workspace.classList.remove('hidden'); findButton.disabled = false; $('#imageInfo').textContent = `${image.naturalWidth} × ${image.naturalHeight}`; latestMatches = []; lastBatch = null; resultList.innerHTML = ''; countBadge.textContent = '尚未辨識'; downloadButton.classList.add('hidden'); setStatus('圖片已載入。輸入想找的文字後開始辨識。'); draw(); }; image.src = reader.result; }; reader.readAsDataURL(file); }
dropZone.onclick = () => input.click(); input.onchange = event => loadFile(event.target.files[0]); ['dragenter', 'dragover'].forEach(type => dropZone.addEventListener(type, event => { event.preventDefault(); dropZone.classList.add('dragging'); })); ['dragleave', 'drop'].forEach(type => dropZone.addEventListener(type, event => { event.preventDefault(); dropZone.classList.remove('dragging'); })); dropZone.addEventListener('drop', event => loadFile(event.dataTransfer.files[0])); dropZone.onkeydown = event => { if (event.key === 'Enter' || event.key === ' ') input.click(); }; findButton.onclick = recognise; targetText.addEventListener('keydown', event => { if (event.key === 'Enter') recognise(); }); matchMode.addEventListener('change', recompute); scoreThresh.addEventListener('input', () => { threshValue.textContent = Number(scoreThresh.value).toFixed(2); recompute(); }); downloadButton.onclick = () => { const link = document.createElement('a'); link.download = `${originalFileName}-已標記.png`; link.href = canvas.toDataURL('image/png'); link.click(); };
