import { PaddleOCR } from '@paddleocr/paddleocr-js';
import { matchItems, matchBbox, uniqueMatches } from './match.js';
const $ = selector => document.querySelector(selector);
const input = $('#imageInput'), dropZone = $('#dropZone'), cameraButton = $('#cameraButton'), cameraPanel = $('#cameraPanel'), cameraVideo = $('#cameraVideo'), captureButton = $('#captureButton'), closeCameraButton = $('#closeCameraButton'), captureCanvas = $('#captureCanvas'), findButton = $('#findButton'), targetText = $('#targetText'), matchMode = $('#matchMode'), verified = $('#verified'), scoreThresh = $('#scoreThresh'), threshValue = $('#threshValue'), workspace = $('#workspace'), canvas = $('#resultCanvas'), ctx = canvas.getContext('2d'), status = $('#status'), cameraStatus = $('#cameraStatus'), resultList = $('#resultList'), countBadge = $('#countBadge'), downloadButton = $('#downloadButton');
let image = null, imageFile = null, cameraStream = null, cameraRecognitionTimer = null, cameraRecognitionInFlight = false, ocr = null, originalFileName = 'marked-image', latestMatches = [], lastBatch = null;
const CAMERA_SCAN_INTERVAL = 1800;
function setStatus(message) { status.textContent = message; }
function roundRectPath(x, y, w, h, r) { const radius = Math.max(0, Math.min(r, w / 2, h / 2)); ctx.beginPath(); ctx.moveTo(x + radius, y); ctx.arcTo(x + w, y, x + w, y + h, radius); ctx.arcTo(x + w, y + h, x, y + h, radius); ctx.arcTo(x, y + h, x, y, radius); ctx.arcTo(x, y, x + w, y, radius); ctx.closePath(); }
function draw(matches = []) { if (!image) return; canvas.width = image.naturalWidth; canvas.height = image.naturalHeight; ctx.drawImage(image, 0, 0); const scale = Math.max(2, canvas.width / 800); ctx.fillStyle = 'rgba(255, 212, 80, .42)'; matches.forEach(match => { const { x0, y0, x1, y1 } = matchBbox(match); const padX = scale * 2.5, padY = Math.max(scale * 2.5, (y1 - y0) * .22); const left = Math.max(0, x0 - padX), top = Math.max(0, y0 - padY), right = Math.min(canvas.width, x1 + padX), bottom = Math.min(canvas.height, y1 + padY); roundRectPath(left, top, right - left, bottom - top, scale * 3); ctx.fill(); }); }
function escapeHtml(value) { const el = document.createElement('div'); el.textContent = value; return el.innerHTML; }
function showMatches(matches) { latestMatches = matches; draw(matches); resultList.innerHTML = ''; countBadge.textContent = `${matches.length} 筆結果`; if (!matches.length) { setStatus('找不到相符文字。可降低最低信心度、使用擴大搜尋，或檢查輸入文字。'); downloadButton.classList.add('hidden'); return; } setStatus(`已標記 ${matches.length} 個相符位置。`); downloadButton.classList.remove('hidden'); matches.forEach((match, index) => { const li = document.createElement('li'); li.innerHTML = `<span class="match-text">${index + 1}. ${escapeHtml(match.text)}</span><span class="meta">信心度 ${Math.round(match.item.score * 100)}%</span>`; li.onclick = () => { draw([match]); canvas.scrollIntoView({ behavior: 'smooth', block: 'center' }); setTimeout(() => draw(latestMatches), 1300); }; resultList.appendChild(li); }); }
function recompute() { if (!lastBatch) return; showMatches(uniqueMatches(matchItems(lastBatch.items, lastBatch.query, matchMode.value, Number(scoreThresh.value)))); }
async function ensureOcr() { if (ocr) return ocr; ocr = await PaddleOCR.create({ textDetectionModelName: 'PP-OCRv6_small_det', textDetectionModelAsset: { url: '/models/PP-OCRv6_small_det_onnx_infer.tar' }, textRecognitionModelName: 'PP-OCRv6_small_rec', textRecognitionModelAsset: { url: '/models/PP-OCRv6_small_rec_onnx_infer.tar' }, ortOptions: { backend: 'wasm', wasmPaths: '/vendor/onnxruntime-web/dist/' } }); return ocr; }
async function requestOcr() { if (!imageFile) throw new Error('請先選擇圖片。'); const scale = verified.checked ? 2 : 1; let source = imageFile; if (scale > 1) { const bitmap = await createImageBitmap(imageFile); const upscaleCanvas = document.createElement('canvas'); upscaleCanvas.width = bitmap.width * scale; upscaleCanvas.height = bitmap.height * scale; upscaleCanvas.getContext('2d').drawImage(bitmap, 0, 0, upscaleCanvas.width, upscaleCanvas.height); bitmap.close(); const blob = await new Promise(resolve => upscaleCanvas.toBlob(resolve, 'image/png')); if (!blob) throw new Error('無法放大圖片。'); source = new File([blob], imageFile.name.replace(/\.[^.]+$/, '') + '-upscaled.png', { type: 'image/png' }); } const engine = await ensureOcr(); const results = await engine.predict(source, { useDocOrientationClassify: false, useDocUnwarping: false, useTextlineOrientation: false }); const items = results[0]?.items || []; return scale === 1 ? items : items.map(item => ({ ...item, poly: item.poly.map(([x, y]) => [x / scale, y / scale]) })); }
async function recognise() { const query = targetText.value; if (!image || !query) { setStatus('請先上傳圖片並輸入要尋找的文字。'); return; } findButton.disabled = true; resultList.innerHTML = ''; countBadge.textContent = '辨識中'; try { setStatus('PaddleOCR 正在辨識圖片文字…首次使用可能需要下載模型，請稍候。'); lastBatch = { items: await requestOcr(), query }; recompute(); } catch (error) { console.error(error); setStatus(`辨識失敗：${error.message}`); countBadge.textContent = '發生錯誤'; } finally { findButton.disabled = false; } }
function loadFile(file, autoRecognise = false) { if (!file || !file.type.startsWith('image/')) { setStatus('請選擇圖片檔案。'); return; } const reader = new FileReader(); reader.onload = () => { image = new Image(); image.onload = () => { imageFile = file; originalFileName = file.name.replace(/\.[^.]+$/, '') || originalFileName; workspace.classList.remove('hidden'); findButton.disabled = false; $('#imageInfo').textContent = `${image.naturalWidth} × ${image.naturalHeight}`; latestMatches = []; lastBatch = null; resultList.innerHTML = ''; countBadge.textContent = '尚未辨識'; downloadButton.classList.add('hidden'); setStatus('圖片已載入。輸入想找的文字後開始辨識。'); draw(); if (autoRecognise && targetText.value.trim()) recognise(); }; image.src = reader.result; }; reader.readAsDataURL(file); }
function stopCamera() { if (cameraRecognitionTimer) { clearInterval(cameraRecognitionTimer); cameraRecognitionTimer = null; } if (cameraStream) { cameraStream.getTracks().forEach(track => track.stop()); cameraStream = null; } cameraVideo.srcObject = null; cameraPanel.classList.add('hidden'); }
function captureCameraFrame() { return new Promise(resolve => { if (!cameraVideo.videoWidth || !cameraVideo.videoHeight) return resolve(null); captureCanvas.width = cameraVideo.videoWidth; captureCanvas.height = cameraVideo.videoHeight; captureCanvas.getContext('2d').drawImage(cameraVideo, 0, 0); captureCanvas.toBlob(resolve, 'image/jpeg', 0.88); }); }
async function updateCameraPreview(file) { const url = URL.createObjectURL(file); const preview = new Image(); await new Promise((resolve, reject) => { preview.onload = resolve; preview.onerror = reject; preview.src = url; }); URL.revokeObjectURL(url); image = preview; imageFile = file; originalFileName = file.name.replace(/\.[^.]+$/, '') || originalFileName; workspace.classList.remove('hidden'); findButton.disabled = false; $('#imageInfo').textContent = `${image.naturalWidth} × ${image.naturalHeight}`; draw(); }
async function recogniseCameraFrame() { if (!cameraStream || cameraRecognitionInFlight) return; const query = targetText.value.trim(); if (!query) { cameraStatus.textContent = '請先輸入要尋找的文字；輸入後會自動開始辨識。'; return; } cameraRecognitionInFlight = true; const stream = cameraStream; try { const blob = await captureCameraFrame(); if (!blob || stream !== cameraStream) return; const file = new File([blob], `camera-${Date.now()}.jpg`, { type: 'image/jpeg' }); await updateCameraPreview(file); if (stream !== cameraStream) return; cameraStatus.textContent = '正在辨識相機畫面…'; setStatus('PaddleOCR 正在辨識相機畫面…'); lastBatch = { items: await requestOcr(), query }; if (stream !== cameraStream) return; recompute(); cameraStatus.textContent = `持續辨識中（每 ${CAMERA_SCAN_INTERVAL / 1000} 秒更新一次）。`; } catch (error) { console.error(error); cameraStatus.textContent = `相機辨識失敗：${error.message}`; setStatus(cameraStatus.textContent); } finally { cameraRecognitionInFlight = false; } }
function startCameraRecognition() { if (cameraRecognitionTimer) clearInterval(cameraRecognitionTimer); cameraStatus.textContent = targetText.value.trim() ? '正在開始自動辨識…' : '請先輸入要尋找的文字；輸入後會自動開始辨識。'; recogniseCameraFrame(); cameraRecognitionTimer = setInterval(recogniseCameraFrame, CAMERA_SCAN_INTERVAL); }
async function openCamera() { if (!navigator.mediaDevices?.getUserMedia) { setStatus('目前瀏覽器不支援相機功能，請改用上傳圖片。'); return; } stopCamera(); cameraPanel.classList.remove('hidden'); cameraStatus.textContent = '正在啟動相機…'; try { cameraStream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: { ideal: 'environment' } }, audio: false }); cameraVideo.srcObject = cameraStream; cameraVideo.onloadedmetadata = () => { cameraVideo.play().catch(() => {}); startCameraRecognition(); }; } catch (error) { cameraStatus.textContent = error.name === 'NotAllowedError' ? '相機權限被拒絕，請在瀏覽器設定中允許後重試。' : `無法啟動相機：${error.message}`; stopCamera(); setStatus(cameraStatus.textContent); } }
function capturePhoto() { if (!cameraVideo.videoWidth || !cameraVideo.videoHeight) { cameraStatus.textContent = '相機畫面尚未準備好，請稍候再試。'; return; } captureCanvas.width = cameraVideo.videoWidth; captureCanvas.height = cameraVideo.videoHeight; captureCanvas.getContext('2d').drawImage(cameraVideo, 0, 0); captureCanvas.toBlob(blob => { if (!blob) { cameraStatus.textContent = '拍照失敗，請重試。'; return; } stopCamera(); loadFile(new File([blob], `camera-${Date.now()}.jpg`, { type: 'image/jpeg' }), true); }, 'image/jpeg', 0.92); }
dropZone.onclick = () => input.click(); cameraButton.onclick = event => { event.stopPropagation(); openCamera(); }; input.onchange = event => loadFile(event.target.files[0]); ['dragenter', 'dragover'].forEach(type => dropZone.addEventListener(type, event => { event.preventDefault(); dropZone.classList.add('dragging'); })); ['dragleave', 'drop'].forEach(type => dropZone.addEventListener(type, event => { event.preventDefault(); dropZone.classList.remove('dragging'); })); dropZone.addEventListener('drop', event => loadFile(event.dataTransfer.files[0])); dropZone.onkeydown = event => { if (event.key === 'Enter' || event.key === ' ') input.click(); }; closeCameraButton.onclick = stopCamera; captureButton.onclick = capturePhoto; findButton.onclick = recognise; targetText.addEventListener('keydown', event => { if (event.key === 'Enter') recognise(); }); targetText.addEventListener('input', () => { if (cameraStream) recogniseCameraFrame(); }); matchMode.addEventListener('change', recompute); scoreThresh.addEventListener('input', () => { threshValue.textContent = Number(scoreThresh.value).toFixed(2); recompute(); }); downloadButton.onclick = () => { const link = document.createElement('a'); link.download = `${originalFileName}-已標記.png`; link.href = canvas.toDataURL('image/png'); link.click(); };
